apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-api
  namespace: student-api
  annotations: {nginx.ingress.kubernetes.io/ssl-redirect: "true"}
spec:
  ingressClassName: nginx
  rules:
    - host: student-api.example.com
      http:
        paths: [{path: /, pathType: Prefix, backend: {service: {name: student-api, port: {number: 80}}}}]
